/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#9dd3aa",
        "surface": "#f9f9f6",
        "tertiary-fixed-dim": "#f0bd8b",
        "background": "#f9f9f6",
        "on-surface-variant": "#414942",
        "on-primary-fixed": "#00210e",
        "surface-container-high": "#e8e8e5",
        "primary-container": "#1a4d2e",
        "on-primary-container": "#88bd95",
        "tertiary": "#452602",
        "on-secondary-container": "#646561",
        "surface-bright": "#f9f9f6",
        "secondary-container": "#e3e3de",
        "on-primary": "#ffffff",
        "primary-fixed": "#b8f0c5",
        "on-tertiary-fixed": "#2c1600",
        "surface-container-low": "#f4f4f0",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c1c9bf",
        "primary": "#00361a",
        "on-surface": "#1a1c1a",
        "secondary-fixed-dim": "#c7c7c2",
        "surface-tint": "#366847",
        "on-tertiary": "#ffffff",
        "surface-container": "#eeeeeb",
        "on-error": "#ffffff",
        "inverse-primary": "#9dd3aa",
        "tertiary-container": "#5f3c15",
        "outline": "#717971",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#1b1c19",
        "on-secondary-fixed-variant": "#464744",
        "surface-dim": "#dadad7",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#1d5031",
        "inverse-surface": "#2f312f",
        "on-tertiary-fixed-variant": "#623f18",
        "on-tertiary-container": "#d9a777",
        "on-error-container": "#93000a",
        "on-background": "#1a1c1a",
        "inverse-on-surface": "#f1f1ed",
        "tertiary-fixed": "#ffdcbd",
        "secondary": "#5e5f5b",
        "surface-container-highest": "#e2e3df",
        "secondary-fixed": "#e3e3de",
        "surface-variant": "#e2e3df"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem",
        "space-xl": "2.5rem",
        "space-lg": "1.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "2rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "label-md": [ "Inter", "sans-serif" ],
        "body-lg": [ "Inter", "sans-serif" ],
        "headline-sm": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-md": [ "Plus Jakarta Sans", "sans-serif" ],
        "body-sm": [ "Inter", "sans-serif" ],
        "headline-lg": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-xl-mobile": [ "Plus Jakarta Sans", "sans-serif" ],
        "display-lg-mobile": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-sm": [ "Inter", "sans-serif" ],
        "body-md": [ "Inter", "sans-serif" ],
        "display-lg": [ "Plus Jakarta Sans", "sans-serif" ],
        "headline-xl": [ "Plus Jakarta Sans", "sans-serif" ],
        "label-lg": [ "Inter", "sans-serif" ]
      },
      fontSize: {
        "label-md": [ "12px", { "lineHeight": "16px", "fontWeight": "600" } ],
        "body-lg": [ "18px", { "lineHeight": "28px", "fontWeight": "400" } ],
        "headline-sm": [ "16px", { "lineHeight": "24px", "fontWeight": "600" } ],
        "headline-md": [ "20px", { "lineHeight": "28px", "fontWeight": "600" } ],
        "body-sm": [ "13px", { "lineHeight": "20px", "fontWeight": "400" } ],
        "headline-lg": [ "24px", { "lineHeight": "32px", "fontWeight": "600" } ],
        "headline-xl-mobile": [ "26px", { "lineHeight": "34px", "fontWeight": "700" } ],
        "display-lg-mobile": [ "36px", { "lineHeight": "44px", "fontWeight": "700" } ],
        "label-sm": [ "11px", { "lineHeight": "14px", "fontWeight": "500" } ],
        "body-md": [ "15px", { "lineHeight": "24px", "fontWeight": "400" } ],
        "display-lg": [ "48px", { "lineHeight": "56px", "fontWeight": "700" } ],
        "headline-xl": [ "32px", { "lineHeight": "40px", "fontWeight": "700" } ],
        "label-lg": [ "14px", { "lineHeight": "20px", "fontWeight": "600" } ]
      }
    }
  },
  plugins: [],
}
